### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by miguelHx** [miguelHx/Bobcat-Courses#3]
- [x] make a better mobile nav-bar (responsive-hide like bootstrap)
- [x] add google analytics to index.html page
- [x] add course title in search bar
- [x] notify user of TBD section
- [x] render sections onto calendar
- [x] refactor code!!!
- [x] export to google calendar button(s)
- [x] login page
- [x] all other buttons from rest api
- [ ] maybe move algorithm to the front end

- [x] fix bug when deleting all saved schedules
- [x] fix bug for saving already saved schedule (index is not correct)
- [ ] add waitlist feature

- [x] other issues posted
- [x] update selectedSections whenever a course is selected
- [x] add boolean property for whether or not a section is selected
- [x] come up with essential properties to use when generating schedules. For example, we need the start time, end time, days, etc. when running the algorithm.
- [x] figure out a way to integrate checkboxes with selectedSections data
- [x] on checkbox change, make a handler function to toggle the selected status of current row
- [x] use CSS Flexbox for aligning course selector and course detail side by side
- [x] disable linked section rows when main component of a course is unchecked
- [x] add course on the left, table and schedules on the right
- [x] remove flex display when browser is less than a certain width
- [x] align things
- [x] update selectedCourse state to undefined on "Remove All" button
- [x] center course information when rendering CourseDetail.js
- [x] add repeated css values to settings as sass variables
